### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by damwhit** [jfangonilo/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [ ] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [x] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The four attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [x] The four methods I chose for **Class #1** represent behaviors or actions.
- [x] I described what the methods do in **Class 1**, including which attributes they use or modify.
- [x] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [x] The four attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [x] The four methods I chose for **Class #2** represent behaviors or actions.
- [x] I described what the methods do in **Class 2**, including which attributes they use or modify.
- [ ] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [ ] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 

### Assessment Results
- [ ] Technical Ready
- [x] Pending
- [ ] Not Technical Ready

**Comment by damwhit** [comment]
@jfangonilo overall, nice work on this! There are a few changes I'd like you to make before we consider you technical ready.

Going back to the rules for whether something is a good attribute:
1. Remember that it's not great to have an attribute with underlying data. In the case of isEmpty, it's only true when currentVolume is 0. Because currentVolume underlies it, there is no need for it. ofAge violates the same rule.
2. Another thing to check is whether something should can stay the same over time. In the case of your age attribute, it's probably not a great attribute in that it will definitely change over time. 
3. You have a customer class, but each of your method names are from the server's perspective?

I'd like you to make the following updates before we consider you `technical ready`:

* [ ] Update class_2.txt so that the rules above are met and naming conventions make sense for the class. You may also change it to be a Server class if you think it's more appropriate.
* [ ] Update class_2_example_object.txt to match your new attribute and method definitions.
